name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Cache Poetry virtualenvs
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: poetry-venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-venv-${{ runner.os }}-

    - name: Install dependencies with Poetry
      run: |
        poetry install --no-root
      working-directory: ${{ github.workspace }}

    - name: Check installed dependencies
      run: |
        poetry show
      working-directory: ${{ github.workspace }}

    - name: Run tests
      run: |
        PYTHONPATH=. poetry run pytest
      working-directory: ${{ github.workspace }}
